import { ActionDirective, ContextDirective, DescriptionDirective, GuardDirective, ImmediateDirective, InitialDirective, Machine, NestedGuardDirective, NestedMachineDirective, NestedMachineWithTransitionDirective, ProducerDirective, ProducerDirectiveWithTransition, ProducerDirectiveWithoutTransition, ShouldFreezeDirective, StateDirective, StatesDirective, TransitionDirective } from './machine/interfaces';
export declare function isValidString(str?: any): str is string;
export declare function isValidObject(obj: any): obj is object;
export declare function isProducer(producer?: any): producer is ProducerDirective;
export declare function isProducerWithTransition(producer?: any): producer is ProducerDirectiveWithTransition;
export declare function isProducerWithoutTransition(producer?: any): producer is ProducerDirectiveWithoutTransition;
export declare function isAction(action?: any): action is ActionDirective;
export declare function isImmediate(immediate?: any): immediate is ImmediateDirective;
export declare function isGuard(guard?: any): guard is GuardDirective;
export declare function isNestedGuard(guard?: any): guard is NestedGuardDirective;
export declare function isTransition(transition?: any): transition is TransitionDirective;
export declare function hasTransition(state: StateDirective, transition: string): boolean;
export declare function hasState(machine: Machine, state: string): boolean;
export declare function isNestedMachineDirective(machine?: any): machine is NestedMachineDirective;
export declare function isNestedMachineWithTransitionDirective(machine?: any): machine is NestedMachineWithTransitionDirective;
export declare function isMachine(machine?: any): machine is Machine;
export declare function isStateDirective(state?: any): state is StateDirective;
export declare function isContextDirective(context?: any): context is ContextDirective;
export declare function isStatesDirective(states?: any): states is StatesDirective;
export declare function isShouldFreezeDirective(shouldFreeze?: any): shouldFreeze is ShouldFreezeDirective;
export declare function isInitialDirective(initial?: any): initial is InitialDirective;
export declare function isDescriptionDirective(description?: any): description is DescriptionDirective;
export declare function deepFreeze(obj: any): any;
export declare function cloneContext(context: any, weakMap?: WeakMap<object, any>): any;
