---
title: Login
---

stateDiagram-v2

classDef danger fill:#f8d7da,stroke:#721c24,stroke-width:2px,text-align:left,color:#721c24
classDef warning fill:#fff3cd,stroke:#856404,stroke-width:2px,text-align:left,color:#856404
classDef success fill:#d4edda,stroke:#155724,stroke-width:2px,text-align:left,color:#155724
classDef primary fill:#cce5ff,stroke:#004085,stroke-width:2px,text-align:left,color:#004085
classDef info fill:#d1ecf1,stroke:#0c5460,stroke-width:2px,text-align:left,color:#0c5460
classDef def fill:#f8f9fa,stroke:#6c757d,stroke-width:2px,text-align:left,color:#6c757d

state idle
state authenticating
state authenticated
state error

authenticating: └┬ AP-authenticateUser<br> ├┬ success<br> │└ T-authenticated<br> └┬ failure<br>  └ T-error

[*] --> idle
idle --> authenticating: login
authenticating --> authenticated: authenticated
authenticating --> error: error
authenticated --> idle: logout
error --> idle: retry
error --> authenticating: login
