<template><div><hr>
<h2 id="simple-example" tabindex="-1"><a class="header-anchor" href="#simple-example" aria-hidden="true">#</a> Simple example</h2>
<figure><img src="/media/toggle-machine-diagram.svg" alt=""><figcaption>Toggle machine diagram</figcaption></figure>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #22272e"><code><span class="line"><span style="color: #F47067">import</span><span style="color: #ADBAC7"> {machine, states, state, initial, transition, invoke} </span><span style="color: #F47067">from</span><span style="color: #ADBAC7"> </span><span style="color: #96D0FF">&#39;x-robot&#39;</span><span style="color: #ADBAC7">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">stoplight</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #96D0FF">&#39;Stoplight&#39;</span><span style="color: #ADBAC7">,</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">states</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;green&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;yellow&#39;</span><span style="color: #ADBAC7">)),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;yellow&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;red&#39;</span><span style="color: #ADBAC7">)),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;red&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;green&#39;</span><span style="color: #ADBAC7">))</span></span>
<span class="line"><span style="color: #ADBAC7">  ),</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">initial</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;green&#39;</span><span style="color: #ADBAC7">)</span></span>
<span class="line"><span style="color: #ADBAC7">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #768390">// stoplight.current === &#39;green&#39; because is the initial state</span></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(stoplight, </span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">); </span><span style="color: #768390">// stoplight.current === &#39;yellow&#39;</span></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(stoplight, </span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">); </span><span style="color: #768390">// stoplight.current === &#39;red&#39;</span></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(stoplight, </span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">); </span><span style="color: #768390">// stoplight.current === &#39;green&#39; </span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="async-example" tabindex="-1"><a class="header-anchor" href="#async-example" aria-hidden="true">#</a> Async example</h2>
<figure><img src="/media/fetch-machine-diagram.svg" alt=""><figcaption>Fetch machine diagram</figcaption></figure>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #22272e"><code><span class="line"><span style="color: #F47067">import</span><span style="color: #ADBAC7"> {machine, states, state, initial, transition, invoke, action, producer} </span><span style="color: #F47067">from</span><span style="color: #ADBAC7"> </span><span style="color: #96D0FF">&#39;x-robot&#39;</span><span style="color: #ADBAC7">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #768390">// Action</span></span>
<span class="line"><span style="color: #F47067">async</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">function</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">fetchDog</span><span style="color: #ADBAC7">() {</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #F47067">let</span><span style="color: #ADBAC7"> response </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">await</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">fetch</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;https://dog.ceo/api/breeds/image/random&#39;</span><span style="color: #ADBAC7">);</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #F47067">let</span><span style="color: #ADBAC7"> json </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">await</span><span style="color: #ADBAC7"> response.</span><span style="color: #DCBDFB">json</span><span style="color: #ADBAC7">();</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #F47067">return</span><span style="color: #ADBAC7"> json.data;</span></span>
<span class="line"><span style="color: #ADBAC7">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #768390">// Producers</span></span>
<span class="line"><span style="color: #F47067">function</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">assignDog</span><span style="color: #ADBAC7">(</span><span style="color: #F69D50">context</span><span style="color: #ADBAC7">, </span><span style="color: #F69D50">dog</span><span style="color: #ADBAC7">) {</span></span>
<span class="line"><span style="color: #ADBAC7">  context.dog </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> dog;</span></span>
<span class="line"><span style="color: #ADBAC7">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F47067">function</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">assignError</span><span style="color: #ADBAC7">(</span><span style="color: #F69D50">context</span><span style="color: #ADBAC7">, </span><span style="color: #F69D50">error</span><span style="color: #ADBAC7">) {</span></span>
<span class="line"><span style="color: #ADBAC7">  context.error </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> error;</span></span>
<span class="line"><span style="color: #ADBAC7">}</span></span>
<span class="line"></span>
<span class="line"><span style="color: #768390">// Machine definition</span></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">fetchMachine</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #96D0FF">&#39;Dog API&#39;</span><span style="color: #ADBAC7">,</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">initial</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;idle&#39;</span><span style="color: #ADBAC7">),</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">context</span><span style="color: #ADBAC7">({</span></span>
<span class="line"><span style="color: #ADBAC7">    dog: </span><span style="color: #6CB6FF">null</span><span style="color: #ADBAC7">,</span></span>
<span class="line"><span style="color: #ADBAC7">    error: </span><span style="color: #6CB6FF">null</span></span>
<span class="line"><span style="color: #ADBAC7">  }),</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">states</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;idle&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;fetch&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;loading&#39;</span><span style="color: #ADBAC7">)),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">      </span><span style="color: #96D0FF">&#39;loading&#39;</span><span style="color: #ADBAC7">,</span></span>
<span class="line"><span style="color: #ADBAC7">      </span><span style="color: #DCBDFB">action</span><span style="color: #ADBAC7">(fetchDog, </span></span>
<span class="line"><span style="color: #ADBAC7">        </span><span style="color: #DCBDFB">producer</span><span style="color: #ADBAC7">(assignDog, </span><span style="color: #96D0FF">&#39;resolved&#39;</span><span style="color: #ADBAC7">), </span></span>
<span class="line"><span style="color: #ADBAC7">        </span><span style="color: #DCBDFB">producer</span><span style="color: #ADBAC7">(assignError, </span><span style="color: #96D0FF">&#39;rejected&#39;</span><span style="color: #ADBAC7">)</span></span>
<span class="line"><span style="color: #ADBAC7">      ), </span></span>
<span class="line"><span style="color: #ADBAC7">      </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;cancel&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;idle&#39;</span><span style="color: #ADBAC7">)</span></span>
<span class="line"><span style="color: #ADBAC7">    ),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;resolved&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">immediate</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;idle&#39;</span><span style="color: #ADBAC7">)),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;rejected&#39;</span><span style="color: #ADBAC7">)</span></span>
<span class="line"><span style="color: #ADBAC7">  )</span></span>
<span class="line"><span style="color: #ADBAC7">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #768390">// fetchMachine.current === &#39;idle&#39; because is the initial state</span></span>
<span class="line"><span style="color: #F47067">await</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(fetchMachine, </span><span style="color: #96D0FF">&#39;fetch&#39;</span><span style="color: #ADBAC7">);</span></span>
<span class="line"><span style="color: #768390">// fetchMachine.current === &#39;idle&#39; because the action was resolved and transitioned to idle</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="nested-machines" tabindex="-1"><a class="header-anchor" href="#nested-machines" aria-hidden="true">#</a> Nested machines</h2>
<figure><img src="/media/stoplight-machine-diagram.svg" alt=""><figcaption>Stoplight machine diagram</figcaption></figure>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #22272e"><code><span class="line"><span style="color: #F47067">import</span><span style="color: #ADBAC7"> {machine, states, state, initial, transition, invoke, nested, guard} </span><span style="color: #F47067">from</span><span style="color: #ADBAC7"> </span><span style="color: #96D0FF">&#39;x-robot&#39;</span><span style="color: #ADBAC7">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">stopwalk</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #96D0FF">&#39;Stopwalk&#39;</span><span style="color: #ADBAC7">,</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">states</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;wait&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;start&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;walk&#39;</span><span style="color: #ADBAC7">)), </span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;walk&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;stop&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;wait&#39;</span><span style="color: #ADBAC7">))</span></span>
<span class="line"><span style="color: #ADBAC7">  ),</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">initial</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;wait&#39;</span><span style="color: #ADBAC7">)</span></span>
<span class="line"><span style="color: #ADBAC7">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #768390">// Guard to prevent the machine to transition to &#39;green&#39; if the stopwalk machine is in &#39;walk&#39; state</span></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">canGoToGreen</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> () </span><span style="color: #F47067">=&gt;</span><span style="color: #ADBAC7"> {</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #F47067">return</span><span style="color: #ADBAC7"> stopwalk.current </span><span style="color: #F47067">===</span><span style="color: #ADBAC7"> </span><span style="color: #96D0FF">&#39;wait&#39;</span><span style="color: #ADBAC7">;</span></span>
<span class="line"><span style="color: #ADBAC7">};</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">stoplight</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #96D0FF">&#39;Stoplight&#39;</span><span style="color: #ADBAC7">,</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">states</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;green&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;yellow&#39;</span><span style="color: #ADBAC7">)),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;yellow&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;red&#39;</span><span style="color: #ADBAC7">)),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">      </span><span style="color: #96D0FF">&#39;red&#39;</span><span style="color: #ADBAC7">, </span></span>
<span class="line"><span style="color: #ADBAC7">      </span><span style="color: #DCBDFB">nested</span><span style="color: #ADBAC7">(stopwalk, </span><span style="color: #96D0FF">&#39;start&#39;</span><span style="color: #ADBAC7">), </span></span>
<span class="line"><span style="color: #ADBAC7">      </span><span style="color: #DCBDFB">immediate</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;green&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">guard</span><span style="color: #ADBAC7">(canGoToGreen))</span></span>
<span class="line"><span style="color: #ADBAC7">    )</span></span>
<span class="line"><span style="color: #ADBAC7">  ),</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">initial</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;green&#39;</span><span style="color: #ADBAC7">)</span></span>
<span class="line"><span style="color: #ADBAC7">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #768390">// stopwalk.current === &#39;wait&#39; because is the initial state</span></span>
<span class="line"><span style="color: #768390">// stoplight.current === &#39;green&#39; because is the initial state</span></span>
<span class="line"></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(stoplight, </span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">);</span></span>
<span class="line"><span style="color: #768390">// stopwalk.current === &#39;wait&#39;</span></span>
<span class="line"><span style="color: #768390">// stoplight.current === &#39;yellow&#39; because the transition was invoked</span></span>
<span class="line"></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(stoplight, </span><span style="color: #96D0FF">&#39;next&#39;</span><span style="color: #ADBAC7">);</span></span>
<span class="line"><span style="color: #768390">// stopwalk.current === &#39;walk&#39; because the stoplight transition invoked the stopwalk transition `start`</span></span>
<span class="line"><span style="color: #768390">// stoplight.current === &#39;red&#39; because the transition was invoked</span></span>
<span class="line"></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(stoplight, </span><span style="color: #96D0FF">&#39;red.stop&#39;</span><span style="color: #ADBAC7">); </span><span style="color: #768390">// Invoke the stopwalk transition stop from the stoplight machine</span></span>
<span class="line"><span style="color: #768390">// stopwalk.current === &#39;wait&#39; because the stop transition was invoked</span></span>
<span class="line"><span style="color: #768390">// stoplight.current === &#39;green&#39; because the immediate transition was invoked and the guard was true</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="parallel-states" tabindex="-1"><a class="header-anchor" href="#parallel-states" aria-hidden="true">#</a> Parallel states</h2>
<figure><img src="/media/word-machine-diagram.svg" alt=""><figcaption>Word machine diagram</figcaption></figure>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: #22272e"><code><span class="line"><span style="color: #F47067">import</span><span style="color: #ADBAC7"> {machine, states, state, initial, transition, invoke, parallel, getState} </span><span style="color: #F47067">from</span><span style="color: #ADBAC7"> </span><span style="color: #96D0FF">&#39;x-robot&#39;</span><span style="color: #ADBAC7">;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">boldMachine</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;Bold&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">states</span><span style="color: #ADBAC7">(</span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">)), </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">))), </span><span style="color: #DCBDFB">initial</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">));</span></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">underlineMachine</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;Underline&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">states</span><span style="color: #ADBAC7">(</span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">)), </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">))), </span><span style="color: #DCBDFB">initial</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">));</span></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">italicsMachine</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;Italics&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">states</span><span style="color: #ADBAC7">(</span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">)), </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;on&#39;</span><span style="color: #ADBAC7">))), </span><span style="color: #DCBDFB">initial</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;off&#39;</span><span style="color: #ADBAC7">));</span></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">listMachine</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #96D0FF">&#39;List&#39;</span><span style="color: #ADBAC7">,</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">states</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;none&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;bullets&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;bullets&#39;</span><span style="color: #ADBAC7">), </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;numbers&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;numbers&#39;</span><span style="color: #ADBAC7">)),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;bullets&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;none&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;none&#39;</span><span style="color: #ADBAC7">)),</span></span>
<span class="line"><span style="color: #ADBAC7">    </span><span style="color: #DCBDFB">state</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;numbers&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #DCBDFB">transition</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;none&#39;</span><span style="color: #ADBAC7">, </span><span style="color: #96D0FF">&#39;none&#39;</span><span style="color: #ADBAC7">))</span></span>
<span class="line"><span style="color: #ADBAC7">  ),</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">initial</span><span style="color: #ADBAC7">(</span><span style="color: #96D0FF">&#39;none&#39;</span><span style="color: #ADBAC7">)</span></span>
<span class="line"><span style="color: #ADBAC7">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #F47067">const</span><span style="color: #ADBAC7"> </span><span style="color: #6CB6FF">wordMachine</span><span style="color: #ADBAC7"> </span><span style="color: #F47067">=</span><span style="color: #ADBAC7"> </span><span style="color: #DCBDFB">machine</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #96D0FF">&#39;Word Machine&#39;</span><span style="color: #ADBAC7">,</span></span>
<span class="line"><span style="color: #ADBAC7">  </span><span style="color: #DCBDFB">parallel</span><span style="color: #ADBAC7">(</span></span>
<span class="line"><span style="color: #ADBAC7">    boldMachine,</span></span>
<span class="line"><span style="color: #ADBAC7">    underlineMachine,</span></span>
<span class="line"><span style="color: #ADBAC7">    italicsMachine,</span></span>
<span class="line"><span style="color: #ADBAC7">    listMachine</span></span>
<span class="line"><span style="color: #ADBAC7">  )</span></span>
<span class="line"><span style="color: #ADBAC7">);</span></span>
<span class="line"></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(wordMachine, </span><span style="color: #96D0FF">&#39;bold/on&#39;</span><span style="color: #ADBAC7">); </span><span style="color: #768390">// boldMachine.current === &#39;on&#39;</span></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(wordMachine, </span><span style="color: #96D0FF">&#39;underline/on&#39;</span><span style="color: #ADBAC7">); </span><span style="color: #768390">// underlineMachine.current === &#39;on&#39;</span></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(wordMachine, </span><span style="color: #96D0FF">&#39;italics/on&#39;</span><span style="color: #ADBAC7">); </span><span style="color: #768390">// italicsMachine.current === &#39;on&#39;</span></span>
<span class="line"><span style="color: #DCBDFB">invoke</span><span style="color: #ADBAC7">(wordMachine, </span><span style="color: #96D0FF">&#39;list/bullets&#39;</span><span style="color: #ADBAC7">); </span><span style="color: #768390">// listMachine.current === &#39;bullets&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="color: #DCBDFB">getState</span><span style="color: #ADBAC7">(wordMachine); </span><span style="color: #768390">// { bold: &#39;on&#39;, underline: &#39;on&#39;, italics: &#39;on&#39;, list: &#39;bullets&#39; }</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
